### ISSUE TITLE
[Bug] endless loading

### ISSUE THREAD

**Issue by ZullD** [Physton/sd-webui-prompt-all-in-one#217] opened 2023-09-03 13:03 UTC
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

When an extension is enabled, there is an endless loading on the extensions page. And on pages with hypernet, embedding, lora, checkpoint.

Pressing the "Check for updates" button on extension tab and "Refresh" button on extranets tab helps to load information. But the timer and counter keep running. And the screen remains gray.
![2023-09-03_06-17-16](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/143943046/092e5ab7-9f1c-4f3e-ba3f-86dea6646bad)
![2023-09-03_06-20-09](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/143943046/5a655a11-4d7b-46f1-a216-a171adafdafa)
![2023-09-03_06-25-36](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/143943046/a3e8d647-6a21-4c84-a560-cd3a0523a191)
I cleaned the gradio cache and the pip. Without effect. Disabled all extensions except this one. The same thing. In all browsers. Opera, Edge, Chrome, Firefox. I also cleaned the cache in browsers. It doesn't help.
I have a lot of loras and checkpoints installed. Symbolic links lead to them on different disks.

### Screenshot or log

Absolutely no errors pop up during the load. The load is clean and error-free.

### OS

Windows

### Browser

Chrome

### Stable Diffusion WebUI version

v1.6.0

### Extension version

6a819041

### Python version

3.10.9

### Gradio version

3.41.2 and 3.42.0

**Comment by ZullD** [comment] 2023-09-03 19:43
Now I found out one thing. If you open two windows with automatic1111 and click refresh in one window, and then wait until the tab with extranets is updated and at the moment when it is updated, switch to the second window and open the tab with extranets there. In the second window everything will be displayed normally, without the eternal loading time and gray shroud.

Perhaps  the extension does not allow the web interface to send a signal to update-refresh information automatically after opening the tab with extranets and extensions. This is evidenced by manually launching the refresh and intercepting the response in the second window.

**Comment by Physton** [comment] 2023-09-04 01:54
I don't know how this situation occurred. In theory, this extension should not affect the loading of other functionalities.

Please provide more information for me to investigate:
1. Which translation API are you using?
2. How were your symbolic links created, and what symbolic links exist?
3. Can you package and send the "storage" directory under your plugin directory to my email: physton@163.com?

**Comment by ZullD** [comment] 2023-09-04 05:31
Hello! 

I use the API from yandex. But this does not affect in any way, since with a clean installation of the extension and disabling the translation function, exactly the same thing happens.

In the following directories inside the stable-diffusion-webui folder, I have created many symbolic links leading to different disks. 

stable-diffusion-webui\models\Lora\
stable-diffusion-webui\models\LyCORIS\
stable-diffusion-webui\models\Stable-diffusion\

To be precise, on four different disks. About 15-20 links in each of these directories (Lora, LyCORIS, Stable-diffusion). And in total I have a little more than 3000 loras and about 500 checkpoints.

Symbolic links are created by a regular command in windows. This one.

mklink /j "C:\dir1" "D:\dir2"

I sent the information from storage to your email.

Thanks for the great extension. It is very functional!

**Comment by Physton** [comment] 2023-09-04 05:33
Sorry, I accidentally closed this issue.
I will take some time to carefully troubleshoot this issue.

**Comment by Physton** [comment] 2023-09-05 04:19
I used the storage file you provided and created the same symbolic link as you did, but I didn't test for this issue. Everything is working fine.

**Comment by Physton** [comment] 2023-09-05 04:25
I'm unable to reproduce the issue, so I don't know how to fix it.

**Comment by Physton** [comment] 2023-09-07 08:36
Just discovered that the code submitted in PR #214 causes the webpage to freeze for at least 10 seconds or more after each refresh. Therefore, I have disabled the code submitted in PR #214 for now. It's possible that this code is causing your issue. You can try again.

**Comment by ZullD** [comment] 2023-09-07 09:41
Unfortunately, it didn't help. Sadly. But in any case, thank you so much for the great extension! And thank you for continuing to improve it!
Apparently in my case this is some so specific bug. :-)

**Comment by ZullD** [comment] 2023-09-12 11:23
I figured out the problem in detail. And here's what I found out. The extension cannot work with more than 2000 loras. It's not about symbolic links, the problem is precisely in excess of the amount of loras or other hypernetworks (but I have more than 3500 thousand lora). I consistently added the amount of lora in the catalog (disabling symbolic links completely) and at a certain point, when exceeding 2000, everything began to hang with endless loading. The extension simply cannot digest such a large number of loras.

I did all this on a clean system where there was nothing else. The automatic was clean and just installed.

**Comment by Physton** [comment] 2023-09-12 12:31
I'm glad you found the cause. However, fixing this bug is not easy. It requires downloading over 2000 Lora for testing, and I will take the time to do that. Additionally, have you used the Civitai hepler to generate info files for these Lora?

**Comment by ZullD** [comment] 2023-09-12 19:08
Definitely. If we take into account embeddings, hypernet, lora, lycoris and checkpoints, then the figure is closer to 3000.

**Comment by ZullD** [comment] 2023-09-12 20:15
And one more clarification. It is the number of files that matters. After a new scan, civitaihelper added a json file to each lora, embeddings, etc. Consequently, the total number of files increased by another quarter (it was 9000 and became 12000) and again there was an endless load.

Summing up the overall result. The total number of files in hypernet directories should not exceed 9000 (3000 directly by loras and so on and 3000 info and 3000 pictures) otherwise this bug occurs with infinite loading.

I did everything I could to catch and understand the reason for the error. I hope this information will be useful.

**Comment by Physton** [comment] 2023-09-14 03:14
Update to the latest version and see if it resolves your issue.

**Comment by ZullD** [comment] 2023-09-14 08:01
Yes! You fixed it! That's great! Thanks!

**Closed** 2023-09-14 10:21 UTC
